### PR TITLE
Adding a form section to the mobile version of the portfolio

### PR DESCRIPTION
**Pull request by sinruidotec**
I am working on improving the portfolio project and its features.

In this Milestone:

- The pair programming modality is used to implement the required annexes to the portfolio.
- The form section with the required fields is added to the index.html file.
- The styles of the form are modified in the file styles.css.
- Stylelint errors fixed.

### CODE REVIEW

**Comment by sinruidotec** [comment]
⚠️ **I kindly ask you to take into account the errors that exist with the linters with which many people are having problems this week, I asked the community about them and they told me to send the project anyway** 🙏🏼

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @sinruidotec , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

🚨 Oh no! It seems that your project submission is invalid due to stylelint errors. While we currently ignoring Weblint errors, it's important to note that your code did not pass the stylelint check. To ensure code quality and maintain consistency, I recommend checking for stylelint errors and addressing them accordingly

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by stanleySimeon — APPROVED** [review]
# Hi @sinruidotec, @shahadat3669, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by franclobo — COMMENTED** [review]
Hi @sinruidotec, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, which is a pair programming project. You should ask for a review and submit this activity individually. It means do not use your partner's PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
